cp-all: define tbl header

define:
	cp sys.c ../linux-4.14.327/kernel/sys.c
tbl:
	cp syscall_64.tbl ../linux-4.14.327/arch/x86/entry/syscalls/syscall_64.tbl

header:
	cp syscalls.h ../linux-4.14.327/include/linux/syscalls.h
